### PR TITLE
feat: replace recharts with react-chartjs-2 to fix security vulnerability

### PR DESCRIPTION
**Pull request by rgodha24**

### CODE REVIEW

**Comment by rgodha24** [comment]
The charts now have weird margins, but I don't know material ui enough to fix it, so if someone else could help that would be great. 
Screen Shot 2022-11-20 at 9 50 35 PM

**Comment by Techno11** [comment]
I'll get this merged in before I start working on the insights for this season. Thanks!

**Comment by rgodha24** [comment]
Sounds good! I'm going to try to add comments for everything I did so everything makes a bit more sense.

**Comment by rgodha24** [comment]
ngl i fixed that bug like 2 weeks ago and forgot to commit + push it, sorry :D. I see that you already did insights for this season, so lmk if you want me to change that to this library or if you want to close this pr

**Pull request closed without merging**
